### ISSUE TITLE
Dead repo???

### ISSUE THREAD

**Issue by kepbod** [unblevable/quick-scope#38]
The latest commit is about one year ago. Is this repo dead? If so, it would be so sad.

**Comment by ahmedelgabri** [comment]
Unfortunately , yeah it looks like it's dead. 

BTW, I had issues with the plugin & tried your fork, works great. Thanks for that 👍

**Comment by kepbod** [comment]
@ahmedelgabri I only merged some RPs from this repo, because I felt still very annoying. I did not want to maintain it instead, so I open this issue to try to find some solutions.

**Comment by ahmedelgabri** [comment]
@kepbod at least those fixes made it work for me so still thanks :) but I get your point.

**Comment by nrobinaubertin** [comment]
@kepbod Thanks for your merges, it worked for me too !

**Comment by bradford-smith94** [comment]
Perhaps @unblevable could transfer the repo to an organization account for the plugin and add maintainers to it like was done for [Vundle](https://github.com/VundleVim/Vundle.vim) and [Syntastic](https://github.com/vim-syntastic/syntastic)? That way we can hopefully revive some active development on this repo rather than a fork.

I would be interested in being a maintainer/developer if there aren't other more qualified volunteers.

**Comment by bradford-smith94** [comment]
I tried to reach out to @unblevable using the email listed on his profile page but haven't heard back.

I have now published [my fork](https://github.com/bradford-smith94/quick-scope) and plan on maintaining it and possibly making improvements.

**Comment by bradford-smith94** [comment]
Great news! @unblevable has reached out to me and added me to the repository. Checkout pull request #40 to follow our progress merging my fork back here.
