### ISSUE TITLE
Allow background color to be configured

### ISSUE THREAD

**Issue by mgaffney** [unblevable/quick-scope#49]
It would be great if `guibg` and `ctermbg` could also be configured.

**Comment by bradford-smith94** [comment]
If you use the new highlight group method of configuration you can.
https://github.com/unblevable/quick-scope#customize-colors

The example shown in the readme doesn't include background colors but because all you are doing is defining a highlight group there is no reason you cannot do this.

You can also take a look at the vim help `:help :highlight` for more information on what you can do with highlight groups.

But basically all you need to do is take the lines from the readme and add what you want for `guibg` or `ctermbg`.

```
highlight QuickScopePrimary guifg='#afff5f' guibg=<something> gui=underline ctermfg=155 ctermbg=<something> cterm=underline
highlight QuickScopeSecondary guifg='#5fffff' guibg=<something> gui=underline ctermfg=81 ctermbg=<something> cterm=underline
```
