### ISSUE TITLE
Add support of cyrillic characters

### ISSUE THREAD

**Issue by d-r-q** [unblevable/quick-scope#7]
Hi, I would like to add support of cyrillic characters to your plugin so I found line where accepted chars defined and added cyrillic chars to it, but it's not works. I have no experience with vimscript, so debug it will require some time for me and I have no time for it right now. Could you please provide me high level plan of how I can add cyrillic chars support?

**Comment by unblevable** [comment]
Were the Cyrillic characters simply not getting highlighted? Adding characters to the `accepted_chars` hash should've worked, unless there is extra work to be done for non-Latin characters that I'm not aware of.

On a related note, I think it would be a useful option for users to add an extended list of characters that can be highlighted. Since that should be simple to implement, I'll try to add this option in the next update.

**Comment by d-r-q** [comment]
No, now Cyrillic characters are not highlighted:
![quick-scope](https://cloud.githubusercontent.com/assets/1336130/9087193/86d59864-3ba2-11e5-9b8d-0c89a0399363.png)

> I'll try to add this option in the next update

Thanks

**Comment by unblevable** [comment]
So after some research, I've realized that I need to adjust the script to work with multibyte characters, which will take some time. This feature probably won't be in the next update, but I will get back to it soon.
